USE `catalog`;

CREATE TABLE `category` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(200) NOT NULL,
	`parent_id` INTEGER,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`parent_id`) REFERENCES `category` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE `product` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(200) NOT NULL,
	`description` TEXT NOT NULL,
	`price` INTEGER NOT NULL,
	`category_id` INTEGER NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`category_id`) REFERENCES `category` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;